// Generated by scripts/palco-scenes/compose.py. Do not edit by hand.
// Native-pixel boxes of the scene art; the DOM overlays scale them by the integer k.
export type SceneName = 'home-wide' | 'home-phone' | '404-wide' | '404-phone' | 'erro-wide' | 'erro-phone' | 'band-wide' | 'band-phone' | 'band-text-wide' | 'band-text-phone' | 'join-wide' | 'join-phone' | 'kicked-wide' | 'kicked-phone' | 'callback-wide' | 'callback-phone';

export interface SceneSprite { id: number; cx: number; top: number; feet: number }
/** Native size of every roster front sprite (join floor). */
export const SPRITE_FRONT = { w: 20, h: 48 } as const;
export interface SceneArt {
  src: string;
  w: number;
  h: number;
  screen: { x: number; y: number; w: number; h: number };
  sprites: SceneSprite[];
  /** Join scenes: feet-centre of the DOM-drawn character. */
  stand?: { cx: number; feet: number };
}

export const SCENES: Record<SceneName, SceneArt> = {
  "home-wide": {
    "src": "/palco/scenes/home-wide.png",
    "w": 480,
    "h": 300,
    "screen": {
      "x": 225,
      "y": 108,
      "w": 131,
      "h": 74
    },
    "sprites": [
      {
        "id": 2,
        "cx": 180,
        "top": 250,
        "feet": 298
      },
      {
        "id": 7,
        "cx": 216,
        "top": 238,
        "feet": 298
      },
      {
        "id": 4,
        "cx": 252,
        "top": 250,
        "feet": 298
      },
      {
        "id": 1,
        "cx": 290,
        "top": 238,
        "feet": 298
      },
      {
        "id": 5,
        "cx": 326,
        "top": 250,
        "feet": 298
      },
      {
        "id": 10,
        "cx": 364,
        "top": 250,
        "feet": 298
      },
      {
        "id": 13,
        "cx": 400,
        "top": 238,
        "feet": 298
      }
    ]
  },
  "home-phone": {
    "src": "/palco/scenes/home-phone.png",
    "w": 195,
    "h": 280,
    "screen": {
      "x": 37,
      "y": 35,
      "w": 120,
      "h": 70
    },
    "sprites": [
      {
        "id": 2,
        "cx": 20,
        "top": 216,
        "feet": 264
      },
      {
        "id": 7,
        "cx": 52,
        "top": 204,
        "feet": 264
      },
      {
        "id": 1,
        "cx": 86,
        "top": 204,
        "feet": 264
      },
      {
        "id": 5,
        "cx": 120,
        "top": 216,
        "feet": 264
      },
      {
        "id": 13,
        "cx": 154,
        "top": 216,
        "feet": 264
      }
    ]
  },
  "404-wide": {
    "src": "/palco/scenes/404-wide.png",
    "w": 480,
    "h": 250,
    "screen": {
      "x": 175,
      "y": 88,
      "w": 131,
      "h": 74
    },
    "sprites": [
      {
        "id": 3,
        "cx": 240,
        "top": 198,
        "feet": 246
      }
    ]
  },
  "404-phone": {
    "src": "/palco/scenes/404-phone.png",
    "w": 195,
    "h": 240,
    "screen": {
      "x": 37,
      "y": 35,
      "w": 120,
      "h": 70
    },
    "sprites": [
      {
        "id": 3,
        "cx": 97,
        "top": 162,
        "feet": 210
      }
    ]
  },
  "erro-wide": {
    "src": "/palco/scenes/erro-wide.png",
    "w": 480,
    "h": 250,
    "screen": {
      "x": 175,
      "y": 88,
      "w": 131,
      "h": 74
    },
    "sprites": [
      {
        "id": 4,
        "cx": 166,
        "top": 202,
        "feet": 250
      },
      {
        "id": 9,
        "cx": 220,
        "top": 202,
        "feet": 250
      },
      {
        "id": 11,
        "cx": 276,
        "top": 202,
        "feet": 250
      },
      {
        "id": 6,
        "cx": 330,
        "top": 202,
        "feet": 250
      }
    ]
  },
  "erro-phone": {
    "src": "/palco/scenes/erro-phone.png",
    "w": 195,
    "h": 240,
    "screen": {
      "x": 37,
      "y": 35,
      "w": 120,
      "h": 70
    },
    "sprites": [
      {
        "id": 4,
        "cx": 46,
        "top": 190,
        "feet": 238
      },
      {
        "id": 9,
        "cx": 96,
        "top": 190,
        "feet": 238
      },
      {
        "id": 11,
        "cx": 146,
        "top": 190,
        "feet": 238
      }
    ]
  },
  "band-wide": {
    "src": "/palco/scenes/band-wide.png",
    "w": 480,
    "h": 130,
    "screen": {
      "x": 175,
      "y": 2,
      "w": 131,
      "h": 74
    },
    "sprites": []
  },
  "band-phone": {
    "src": "/palco/scenes/band-phone.png",
    "w": 195,
    "h": 150,
    "screen": {
      "x": 37,
      "y": 25,
      "w": 120,
      "h": 70
    },
    "sprites": []
  },
  "band-text-wide": {
    "src": "/palco/scenes/band-text-wide.png",
    "w": 480,
    "h": 130,
    "screen": {
      "x": 175,
      "y": 2,
      "w": 131,
      "h": 74
    },
    "sprites": []
  },
  "band-text-phone": {
    "src": "/palco/scenes/band-text-phone.png",
    "w": 195,
    "h": 150,
    "screen": {
      "x": 37,
      "y": 25,
      "w": 120,
      "h": 70
    },
    "sprites": []
  },
  "join-wide": {
    "src": "/palco/scenes/join-wide.png",
    "w": 480,
    "h": 300,
    "screen": {
      "x": 115,
      "y": 102,
      "w": 131,
      "h": 74
    },
    "sprites": [],
    "stand": {
      "cx": 180,
      "feet": 286
    }
  },
  "join-phone": {
    "src": "/palco/scenes/join-phone.png",
    "w": 195,
    "h": 240,
    "screen": {
      "x": 37,
      "y": 35,
      "w": 120,
      "h": 70
    },
    "sprites": [],
    "stand": {
      "cx": 97,
      "feet": 232
    }
  },
  "kicked-wide": {
    "src": "/palco/scenes/kicked-wide.png",
    "w": 480,
    "h": 300,
    "screen": {
      "x": 175,
      "y": 102,
      "w": 131,
      "h": 74
    },
    "sprites": []
  },
  "kicked-phone": {
    "src": "/palco/scenes/kicked-phone.png",
    "w": 195,
    "h": 240,
    "screen": {
      "x": 37,
      "y": 35,
      "w": 120,
      "h": 70
    },
    "sprites": []
  },
  "callback-wide": {
    "src": "/palco/scenes/callback-wide.png",
    "w": 480,
    "h": 250,
    "screen": {
      "x": 175,
      "y": 88,
      "w": 131,
      "h": 74
    },
    "sprites": []
  },
  "callback-phone": {
    "src": "/palco/scenes/callback-phone.png",
    "w": 195,
    "h": 240,
    "screen": {
      "x": 37,
      "y": 35,
      "w": 120,
      "h": 70
    },
    "sprites": []
  }
};
